/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ILYAsquared - Outsourcing Team (https://sketchfab.com/ilyasquared)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steampunk-headphones-64b538e9983f45f18908f2a80251c072
Title: Steampunk Headphones
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { OrbitControls } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/FloatingIcons/steampunk_headphones.glb')
  return (
    <Float>

    
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve000__0.geometry}
        material={materials.RootNode}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.3,0.3,0.3]}
        position={[-13,2.5,4.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001__0.geometry}
        material={materials.RootNode}
        rotation={[0, Math.PI / 2, 0]}
        // scale={[0.3,0.3,0.3]}
        // position={[-13,2.5,4.8]}

      />
      
    </group>
    </Float>
  )
}

useGLTF.preload('/public/FloatingIcons/steampunk_headphones.glb')