/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bossdeff (https://sketchfab.com/bossdeff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dirty-sci-fi-laptop-star-wars-5b4c6b94692643d9ad0ba61dcb4892dc
Title: Dirty Sci-Fi Laptop (Star Wars)
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop/Laptop.gltf')
  // const screenTexture = useTexture('/public/assets/me.jpg')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Laptop_0.geometry}
          material={materials.Laptop}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
        {/* <meshMatcapMaterial map={screenTexture} />   */}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.keys001_Rubber_0.geometry}
          material={materials.Rubber}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[248.603, 248.603, 156.487]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop/Laptop.gltf')
